name: Test NestJS

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: دریافت کد پروژه
        uses: actions/checkout@v4

      - name: نصب Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: نصب پکیج‌ها
        run: npm ci

      - name: اجرای تست
        run: npm run test

      - name: بیلد NestJS
        run: npm run build
